//! IBus Buffalo Input Method Daemon Library.
//!
//! This library provides the core component logic for the IBus Buffalo input method daemon,
//! including configurations, zbus D-Bus interface implementations, and event loop logic.

/// Prints debug messages to stdout only when compiled in debug mode.
macro_rules! debug_println {
    ($($arg:tt)*) => {
        #[cfg(debug_assertions)]
        {
            println!($($arg)*);
        }
    };
}

use buffalo_core::{
    CharsetEncoding, ESTD_FLAGS, Engine, VIETNAMESE_MODE, encode, get_input_method,
    is_word_break_symbol,
};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::env;
use std::fs;
use std::path::PathBuf;
use std::str::FromStr;
use std::sync::Mutex;
use zbus::object_server::SignalEmitter;
use zbus::zvariant::{OwnedObjectPath, OwnedValue, Value};
use zbus::{Connection, connection::Builder, interface};

pub mod x11_helper;

/// Represents an IBus text attribute, defining text formatting like underline, color, etc.
#[derive(
    Serialize,
    Deserialize,
    zbus::zvariant::Type,
    zbus::zvariant::Value,
    zbus::zvariant::OwnedValue,
    Debug,
)]
pub struct IBusAttribute {
    /// Attribute name (always "IBusAttribute").
    pub name: String,
    /// Metadata attachments.
    pub attachments: HashMap<String, OwnedValue>,
    /// Type of attribute.
    pub attr_type: u32,
    /// Value associated with the attribute.
    pub value: u32,
    /// Starting character index in the text.
    pub start_index: u32,
    /// Ending character index in the text.
    pub end_index: u32,
}

/// Represents a list of text attributes in IBus.
#[derive(
    Serialize,
    Deserialize,
    zbus::zvariant::Type,
    zbus::zvariant::Value,
    zbus::zvariant::OwnedValue,
    Debug,
)]
pub struct IBusAttrList {
    /// Struct name (always "IBusAttrList").
    pub name: String,
    /// Metadata attachments.
    pub attachments: HashMap<String, OwnedValue>,
    /// List of serializable attributes.
    pub attributes: Vec<OwnedValue>,
}

/// Represents a piece of text along with its formatting attributes in IBus.
#[derive(
    Serialize,
    Deserialize,
    zbus::zvariant::Type,
    zbus::zvariant::Value,
    zbus::zvariant::OwnedValue,
    Debug,
)]
pub struct IBusText {
    /// Struct name (always "IBusText").
    pub name: String,
    /// Metadata attachments.
    pub attachments: HashMap<String, OwnedValue>,
    /// The actual text string.
    pub text: String,
    /// Attributes associated with the text.
    pub attr_list: OwnedValue,
}

/// Helper function to construct a new `IBusText` without any formatting attributes.
///
/// * `text` - The string slice to wrap.
pub fn new_ibus_text(text: &str) -> IBusText {
    let attr_list = IBusAttrList {
        name: "IBusAttrList".to_string(),
        attachments: HashMap::new(),
        attributes: Vec::new(),
    };
    let attr_list_value = OwnedValue::try_from(attr_list).unwrap();
    IBusText {
        name: "IBusText".to_string(),
        attachments: HashMap::new(),
        text: text.to_string(),
        attr_list: attr_list_value,
    }
}

/// Retrieves the unique machine ID from `/var/lib/dbus/machine-id` or `/etc/machine-id`.
/// Returns an empty string if it cannot be read.
pub fn get_local_machine_id() -> String {
    fs::read_to_string("/var/lib/dbus/machine-id")
        .or_else(|_| fs::read_to_string("/etc/machine-id"))
        .unwrap_or_default()
        .trim()
        .to_string()
}

/// Retrieves the path to the user's config directory, honoring `XDG_CONFIG_HOME`
/// with a fallback to `$HOME/.config`.
pub fn get_user_config_dir() -> PathBuf {
    if let Ok(dir) = env::var("XDG_CONFIG_HOME") {
        PathBuf::from(dir)
    } else {
        let home = env::var("HOME").unwrap_or_default();
        PathBuf::from(home).join(".config")
    }
}

/// Detects the active IBus address by reading the environment variable `IBUS_ADDRESS`
/// or by scanning configuration files generated by IBus for Wayland/X11 sessions.
pub fn get_ibus_address() -> Option<String> {
    if let Ok(addr) = env::var("IBUS_ADDRESS") {
        return Some(addr);
    }

    let machine_id = get_local_machine_id();
    if machine_id.is_empty() {
        return None;
    }

    // Check Wayland
    if let Ok(wayland_display) = env::var("WAYLAND_DISPLAY") {
        let filename = format!("{}-unix-{}", machine_id, wayland_display);
        let path = get_user_config_dir().join("ibus/bus").join(filename);
        if let Ok(content) = fs::read_to_string(path) {
            for line in content.lines() {
                if line.starts_with("IBUS_ADDRESS=") {
                    return Some(line["IBUS_ADDRESS=".len()..].to_string());
                }
            }
        }
    }

    // Check X11
    let display = env::var("DISPLAY").unwrap_or_else(|_| ":0".to_string());
    let display_part = display.split(':').nth(1).unwrap_or("0");
    let display_num = display_part.split('.').next().unwrap_or("0");

    let filename = format!("{}-unix-{}", machine_id, display_num);
    let path = get_user_config_dir().join("ibus/bus").join(filename);
    if let Ok(content) = fs::read_to_string(path) {
        for line in content.lines() {
            if line.starts_with("IBUS_ADDRESS=") {
                return Some(line["IBUS_ADDRESS=".len()..].to_string());
            }
        }
    }

    None
}

/// Mask representing the Shift key state in IBus.
pub const IBUS_SHIFT_MASK: u32 = 1 << 0;
/// Mask representing the Caps Lock key state in IBus.
pub const IBUS_LOCK_MASK: u32 = 1 << 1;
/// Mask representing the Control key state in IBus.
pub const IBUS_CONTROL_MASK: u32 = 1 << 2;
/// Mask representing the Alt/Mod1 key state in IBus.
pub const IBUS_MOD1_MASK: u32 = 1 << 3;
/// Mask representing the Mod4/Super key state in IBus.
pub const IBUS_MOD4_MASK: u32 = 1 << 6;
/// Mask representing the Super key state in IBus.
pub const IBUS_SUPER_MASK: u32 = 1 << 26;
/// Mask representing the Hyper key state in IBus.
pub const IBUS_HYPER_MASK: u32 = 1 << 27;
/// Mask representing the Meta key state in IBus.
pub const IBUS_META_MASK: u32 = 1 << 28;
/// Mask indicating a key release event in IBus.
pub const IBUS_RELEASE_MASK: u32 = 1 << 30;

/// Key code representing the Backspace key.
pub const IBUS_BACKSPACE: u32 = 0xff08;
/// Key code representing the Tab key.
pub const IBUS_TAB: u32 = 0xff09;
/// Key code representing the Left Arrow key.
pub const IBUS_LEFT: u32 = 0xff51;
/// Key code representing the Return/Enter key.
pub const IBUS_RETURN: u32 = 0xff0d;
/// Key code representing the Escape key.
pub const IBUS_ESCAPE: u32 = 0xff1b;

/// Preedit Input Mode: show composition inline with underlining.
pub const PREEDIT_IM: i32 = 1;
/// Surrounding Text Input Mode: edit surrounding characters directly.
pub const SURROUNDING_TEXT_IM: i32 = 2;
/// Backspace Forwarding Input Mode: delete/retype by forwarding backspace keypress events.
pub const BACKSPACE_FORWARDING_IM: i32 = 3;
/// Shift Left Forwarding Input Mode: delete by simulating Shift+Left Arrow selections.
pub const SHIFT_LEFT_FORWARDING_IM: i32 = 4;
/// Forward as Commit Input Mode: commit text by forwarding synthetic keyboard events.
pub const FORWARD_AS_COMMIT_IM: i32 = 5;
/// XTest Fake Key Event Input Mode: simulate X11 keyboard events directly.
pub const XTEST_FAKE_KEY_EVENT_IM: i32 = 6;
/// US Keyboard layout mode (no Vietnamese processing).
pub const US_IM: i32 = 7;

/// Checks if the input mode relies on simulating backspaces to update the buffer.
pub fn is_backspace_mode(im: i32) -> bool {
    matches!(
        im,
        SURROUNDING_TEXT_IM
            | BACKSPACE_FORWARDING_IM
            | SHIFT_LEFT_FORWARDING_IM
            | FORWARD_AS_COMMIT_IM
            | XTEST_FAKE_KEY_EVENT_IM
    )
}

/// Checks if a keysym represents a modifier key itself.
pub fn is_modifier_key(keyval: u32) -> bool {
    // Standard X11 modifier keysyms:
    // 0xffe1 - 0xffee: Shift, Control, Caps_Lock, Shift_Lock, Meta, Alt, Super, Hyper
    // 0xfe03: ISO_Level3_Shift (AltGr)
    // 0xff7e: Mode_switch
    (keyval >= 0xffe1 && keyval <= 0xffee) || keyval == 0xfe03 || keyval == 0xff7e
}

/// Configuration for the IBus Buffalo input method.
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct Config {
    /// Currently selected input method (e.g., "Telex", "VNI").
    pub input_method: String,
    /// Engine flags.
    pub flags: u32,
    /// Output charset encoding (e.g., "Unicode", "TCVN3", "VNI", "VIQR").
    pub charset: String,
}

impl Default for Config {
    fn default() -> Self {
        Self {
            input_method: "Telex".to_string(),
            flags: ESTD_FLAGS,
            charset: "Unicode".to_string(),
        }
    }
}

/// Loads configuration from `$XDG_CONFIG_HOME/ibus-buffalo/config.toml`.
/// Fallbacks to `Config::default()` and saves it if the file does not exist.
pub fn load_config() -> Config {
    let path = get_user_config_dir()
        .join("ibus-buffalo")
        .join("config.toml");
    if let Ok(content) = fs::read_to_string(&path) {
        if let Ok(mut cfg) = toml::from_str::<Config>(&content) {
            if cfg.input_method == "English" {
                cfg.input_method = "Telex".to_string();
                let _ = save_config(&cfg);
            }
            return cfg;
        }
    }
    let cfg = Config::default();
    let _ = save_config(&cfg);
    cfg
}

/// Saves configuration to `$XDG_CONFIG_HOME/ibus-buffalo/config.toml`.
pub fn save_config(cfg: &Config) -> std::io::Result<()> {
    let dir = get_user_config_dir().join("ibus-buffalo");
    fs::create_dir_all(&dir)?;
    let path = dir.join("config.toml");
    let content = toml::to_string_pretty(cfg).unwrap();
    fs::write(path, content)?;
    Ok(())
}

/// Represents a property item in the IBus status menu/bar.
#[derive(
    Serialize,
    Deserialize,
    zbus::zvariant::Type,
    zbus::zvariant::Value,
    zbus::zvariant::OwnedValue,
    Debug,
)]
pub struct IBusProperty {
    /// Property name.
    pub name: String,
    /// Metadata attachments.
    pub attachments: HashMap<String, OwnedValue>,
    /// Unique key string.
    pub key: String,
    /// Type of property (e.g. menu, toggle).
    pub prop_type: u32,
    /// Property label.
    pub label: OwnedValue,
    /// Icon name.
    pub icon: String,
    /// Tooltip text.
    pub tooltip: OwnedValue,
    /// Sensitivity state.
    pub sensitive: bool,
    /// Visibility state.
    pub visible: bool,
    /// Selected/checked state.
    pub state: u32,
    /// Sub-properties (for menu nesting).
    pub sub_props: OwnedValue,
    /// Symbol string.
    pub symbol: OwnedValue,
}

/// Represents a list of IBus properties.
#[derive(
    Serialize,
    Deserialize,
    zbus::zvariant::Type,
    zbus::zvariant::Value,
    zbus::zvariant::OwnedValue,
    Debug,
)]
pub struct IBusPropList {
    /// List name.
    pub name: String,
    /// Metadata attachments.
    pub attachments: HashMap<String, OwnedValue>,
    /// Property elements.
    pub properties: Vec<OwnedValue>,
}

/// Constructs a new `IBusProperty` item.
///
/// * `key` - Unique identifier key.
/// * `prop_type` - Type of the property.
/// * `label` - Label text.
/// * `icon` - Icon name.
/// * `state` - Initial state of the property.
/// * `sub_props` - List of child sub-properties, if any.
pub fn new_ibus_property(
    key: &str,
    prop_type: u32,
    label: &str,
    icon: &str,
    state: u32,
    sub_props: Option<IBusPropList>,
) -> IBusProperty {
    let label_val = OwnedValue::try_from(new_ibus_text(label)).unwrap();
    let tooltip_val = OwnedValue::try_from(new_ibus_text("")).unwrap();
    let symbol_val = OwnedValue::try_from(new_ibus_text("")).unwrap();
    let sub_props_val = if let Some(sp) = sub_props {
        OwnedValue::try_from(sp).unwrap()
    } else {
        let empty_list = IBusPropList {
            name: "IBusPropList".to_string(),
            attachments: HashMap::new(),
            properties: Vec::new(),
        };
        OwnedValue::try_from(empty_list).unwrap()
    };

    IBusProperty {
        name: "IBusProperty".to_string(),
        attachments: HashMap::new(),
        key: key.to_string(),
        prop_type,
        label: label_val,
        icon: icon.to_string(),
        tooltip: tooltip_val,
        sensitive: true,
        visible: true,
        state,
        sub_props: sub_props_val,
        symbol: symbol_val,
    }
}

pub fn get_prop_list(config: &Config) -> IBusPropList {
    let mut properties = Vec::new();

    let about_prop = new_ibus_property("about", 0, "IBus Buffalo", "gtk-about", 0, None);
    properties.push(OwnedValue::try_from(about_prop).unwrap());

    let mut im_subprops = Vec::new();
    let ims = vec!["Telex", "VNI"];
    for im in ims {
        let state = if config.input_method == im { 1 } else { 0 };
        let prop = new_ibus_property(&format!("InputMethod::{}", im), 2, im, "", state, None);
        im_subprops.push(OwnedValue::try_from(prop).unwrap());
    }
    let im_menu = new_ibus_property(
        "input_method_menu",
        3,
        "Kiểu gõ",
        "preferences-desktop",
        0,
        Some(IBusPropList {
            name: "IBusPropList".to_string(),
            attachments: HashMap::new(),
            properties: im_subprops,
        }),
    );
    properties.push(OwnedValue::try_from(im_menu).unwrap());

    // Charset encoding submenu
    let mut charset_subprops = Vec::new();
    for cs in CharsetEncoding::all() {
        let cs_key = cs.to_string();
        let state = if config.charset == cs_key { 1 } else { 0 };
        let prop = new_ibus_property(
            &format!("Charset::{}", cs_key),
            2,
            cs.display_name(),
            "",
            state,
            None,
        );
        charset_subprops.push(OwnedValue::try_from(prop).unwrap());
    }
    let charset_menu = new_ibus_property(
        "charset_menu",
        3,
        "Bảng mã",
        "preferences-desktop-font",
        0,
        Some(IBusPropList {
            name: "IBusPropList".to_string(),
            attachments: HashMap::new(),
            properties: charset_subprops,
        }),
    );
    properties.push(OwnedValue::try_from(charset_menu).unwrap());

    IBusPropList {
        name: "IBusPropList".to_string(),
        attachments: HashMap::new(),
        properties,
    }
}

/// Calculates the suffix to append and the number of backspaces needed to transition
/// from `old_text` to `new_text` in the editor buffer.
///
/// * `new_text` - The target text to be set.
/// * `old_text` - The current text in the buffer.
///
/// Returns a tuple containing the suffix string to append and the backspace count.
pub fn get_offset_runes(new_text: &str, old_text: &str) -> (String, usize) {
    let old_chars: Vec<char> = old_text.chars().collect();
    let new_chars: Vec<char> = new_text.chars().collect();

    let min_len = std::cmp::min(old_chars.len(), new_chars.len());
    let mut offset = 0;
    for i in 0..min_len {
        if old_chars[i] != new_chars[i] {
            break;
        }
        offset += 1;
    }

    let n_backspace = if offset < old_chars.len() {
        old_chars.len() - offset
    } else {
        0
    };

    let suffix: String = new_chars[offset..].iter().collect();
    (suffix, n_backspace)
}

/// Queries the GNOME Shell D-Bus interface to retrieve the window class of the focused window.
pub async fn gnome_get_focus_window_class() -> Option<String> {
    let conn = Connection::session().await.ok()?;
    let js_code = "global.get_window_actors().find(window => !Main.overview.visible && window.meta_window.has_focus()).get_meta_window().get_wm_class()";
    let reply: (bool, String) = conn
        .call_method(
            Some("org.gnome.Shell"),
            "/org/gnome/Shell",
            Some("org.gnome.Shell"),
            "Eval",
            &(js_code,),
        )
        .await
        .ok()?
        .body()
        .deserialize()
        .ok()?;

    if reply.0 {
        let s = reply.1.trim().replace('"', "");
        if s.is_empty() || s == "null" {
            None
        } else {
            Some(s)
        }
    } else {
        let is_overview_js = "Main.overview.visible";
        let is_overview_reply: (bool, String) = conn
            .call_method(
                Some("org.gnome.Shell"),
                "/org/gnome/Shell",
                Some("org.gnome.Shell"),
                "Eval",
                &(is_overview_js,),
            )
            .await
            .ok()?
            .body()
            .deserialize()
            .ok()?;

        if is_overview_reply.0 && is_overview_reply.1 == "true" {
            Some("org.gnome.Overview".to_string())
        } else {
            None
        }
    }
}

/// Retrieves the window class of the currently focused window, checking GNOME Shell via D-Bus
/// and falling back to direct X11 queries.
pub async fn get_focus_window_class() -> String {
    if let Some(wm) = gnome_get_focus_window_class().await {
        return wm;
    }
    if let Some(wm) = x11_helper::x11_get_focus_window_class() {
        return wm;
    }
    String::new()
}

/// The main IBus Engine instance managing state, input method engine, active window tracking,
/// and preedit buffer tracking.
pub struct IBusEngine {
    /// The core buffalo typing engine.
    pub engine: Mutex<Engine>,
    /// The class name of the currently focused window.
    pub wm_class: Mutex<String>,
    /// The last committed text, used for offset calculations.
    pub last_text: Mutex<String>,
}

impl IBusEngine {
    /// Creates a new `IBusEngine` instance.
    pub fn new(engine: Engine) -> Self {
        Self {
            engine: Mutex::new(engine),
            wm_class: Mutex::new(String::new()),
            last_text: Mutex::new(String::new()),
        }
    }
}

#[interface(name = "org.freedesktop.IBus.Engine")]
impl IBusEngine {
    /// D-Bus method invoked by IBus to process key events.
    ///
    /// * `signal_emitter` - Object used to emit D-Bus signals.
    /// * `keyval` - Key symbol value.
    /// * `keycode` - Hardware keycode.
    /// * `state` - Key modifier state mask.
    ///
    /// Returns `true` if the engine handles the key event, or `false` to let the system handle it.
    async fn process_key_event(
        &self,
        #[zbus(signal_emitter)] signal_emitter: SignalEmitter<'_>,
        keyval: u32,
        keycode: u32,
        state: u32,
    ) -> bool {
        debug_println!(
            "--> [D-Bus] ProcessKeyEvent: keyval={:#x}, keycode={}, state={:#x}",
            keyval,
            keycode,
            state
        );
        let handled = self
            .handle_key(&signal_emitter, keyval, keycode, state)
            .await;
        debug_println!("--> [D-Bus] ProcessKeyEvent Result: {}", handled);
        handled
    }

    /// D-Bus method invoked when the input method engine gains focus.
    /// Updates the tracked window class and registers engine properties.
    async fn focus_in(&self, #[zbus(signal_emitter)] signal_emitter: SignalEmitter<'_>) {
        let wm = get_focus_window_class().await;
        println!("FocusIn: window class = {}", wm);
        {
            let mut current_wm = self.wm_class.lock().unwrap();
            if *current_wm != wm {
                *current_wm = wm;
                let mut engine = self.engine.lock().unwrap();
                engine.reset();
                let mut lt = self.last_text.lock().unwrap();
                lt.clear();
            }
        }

        let config = load_config();
        let props = get_prop_list(&config);
        let props_val = OwnedValue::try_from(props).unwrap();
        let _ = Self::register_properties(&signal_emitter, Value::from(props_val)).await;
    }

    /// D-Bus method invoked when the input method engine loses focus.
    async fn focus_out(&self) {}

    /// D-Bus method invoked to reset the engine state.
    async fn reset(&self, #[zbus(signal_emitter)] signal_emitter: SignalEmitter<'_>) {
        self.commit_and_reset(&signal_emitter, PREEDIT_IM).await;
    }

    /// D-Bus methods required by IBus Engine interface but not actively implemented.
    async fn enable(&self) {}
    /// D-Bus methods required by IBus Engine interface but not actively implemented.
    async fn disable(&self) {}
    /// D-Bus methods required by IBus Engine interface but not actively implemented.
    async fn set_cursor_location(&self, _x: i32, _y: i32, _w: i32, _h: i32) {}
    /// D-Bus methods required by IBus Engine interface but not actively implemented.
    async fn set_capabilities(&self, _cap: u32) {}
    /// D-Bus methods required by IBus Engine interface but not actively implemented.
    async fn set_surrounding_text(&self, _text: Value<'_>, _cursor_index: u32, _anchor_pos: u32) {}

    /// D-Bus method invoked when an IBus menu property is clicked or toggled.
    async fn property_activate(
        &self,
        #[zbus(signal_emitter)] signal_emitter: SignalEmitter<'_>,
        prop_name: String,
        prop_state: u32,
    ) {
        println!(
            "PropertyActivate: name = {}, state = {}",
            prop_name, prop_state
        );

        if prop_name == "about" {
            let ui_path = get_ui_executable_path();
            let _ = std::process::Command::new(ui_path).spawn();
            return;
        }

        let mut config = load_config();

        if prop_name.starts_with("InputMethod::") {
            if prop_state == 1 {
                let im = &prop_name["InputMethod::".len()..];
                config.input_method = im.to_string();
                let _ = save_config(&config);
            }
        } else if prop_name.starts_with("Charset::") {
            if prop_state == 1 {
                let cs = &prop_name["Charset::".len()..];
                config.charset = cs.to_string();
                let _ = save_config(&config);
            }
        }

        let active_layout = &config.input_method;
        if let Some(im_def) = get_input_method(active_layout) {
            let mut engine = self.engine.lock().unwrap();
            *engine = Engine::new(im_def, config.flags);
        }

        let props = get_prop_list(&config);
        let props_val = OwnedValue::try_from(props).unwrap();
        let _ = Self::register_properties(&signal_emitter, Value::from(props_val)).await;
    }

    /// D-Bus methods required by IBus Engine interface but not actively implemented.
    async fn property_show(&self, _prop_name: String) {}
    /// D-Bus methods required by IBus Engine interface but not actively implemented.
    async fn property_hide(&self, _prop_name: String) {}
    /// D-Bus methods required by IBus Engine interface but not actively implemented.
    async fn page_up(&self) {}
    /// D-Bus methods required by IBus Engine interface but not actively implemented.
    async fn page_down(&self) {}
    /// D-Bus methods required by IBus Engine interface but not actively implemented.
    async fn cursor_up(&self) {}
    /// D-Bus methods required by IBus Engine interface but not actively implemented.
    async fn cursor_down(&self) {}
    /// D-Bus methods required by IBus Engine interface but not actively implemented.
    async fn candidate_clicked(&self, _index: u32, _button: u32, _state: u32) {}

    /// Signal emitted to commit completed text to the application.
    #[zbus(signal)]
    pub async fn commit_text(
        signal_emitter: &SignalEmitter<'_>,
        text: Value<'_>,
    ) -> zbus::Result<()>;

    /// Signal emitted to update the inline preedit composition text.
    #[zbus(signal)]
    pub async fn update_preedit_text(
        signal_emitter: &SignalEmitter<'_>,
        text: Value<'_>,
        cursor_pos: u32,
        visible: bool,
        mode: u32,
    ) -> zbus::Result<()>;

    /// Signal emitted to hide the inline preedit composition.
    #[zbus(signal)]
    pub async fn hide_preedit_text(signal_emitter: &SignalEmitter<'_>) -> zbus::Result<()>;

    /// Signal emitted to forward key events back to the client application.
    #[zbus(signal)]
    pub async fn forward_key_event(
        signal_emitter: &SignalEmitter<'_>,
        keyval: u32,
        keycode: u32,
        state: u32,
    ) -> zbus::Result<()>;

    /// Signal emitted to delete surrounding text relative to the cursor.
    #[zbus(signal)]
    pub async fn delete_surrounding_text(
        signal_emitter: &SignalEmitter<'_>,
        offset: i32,
        n_chars: u32,
    ) -> zbus::Result<()>;

    /// Signal emitted to register configuration properties with IBus.
    #[zbus(signal)]
    pub async fn register_properties(
        signal_emitter: &SignalEmitter<'_>,
        props: Value<'_>,
    ) -> zbus::Result<()>;

    /// Signal emitted to update specific configuration property states.
    #[zbus(signal)]
    pub async fn update_property(
        signal_emitter: &SignalEmitter<'_>,
        prop: Value<'_>,
    ) -> zbus::Result<()>;
}

impl IBusEngine {
    /// Internal key handler managing layout processing, modifiers check, and keystroke dispatching.
    pub async fn handle_key(
        &self,
        signal_emitter: &SignalEmitter<'_>,
        keyval: u32,
        _keycode: u32,
        state: u32,
    ) -> bool {
        debug_println!(
            "--> handle_key: keyval={:#x}, keycode={}, state={:#x}",
            keyval,
            _keycode,
            state
        );
        let _config = load_config();
        let is_release = (state & IBUS_RELEASE_MASK) != 0;

        if is_release {
            debug_println!("--> handle_key ignored (release event)");
            return false;
        }

        if is_modifier_key(keyval) {
            debug_println!(
                "--> handle_key ignored (modifier key itself: keyval={:#x})",
                keyval
            );
            return false;
        }

        let input_mode = PREEDIT_IM;
        let charset =
            CharsetEncoding::from_str(&_config.charset).unwrap_or(CharsetEncoding::Unicode);
        debug_println!(
            "--> handle_key: input_mode={}, config.input_method='{}', charset='{}'",
            input_mode,
            _config.input_method,
            _config.charset
        );

        let has_modifiers = (state
            & (IBUS_CONTROL_MASK
                | IBUS_MOD1_MASK
                | IBUS_MOD4_MASK
                | IBUS_SUPER_MASK
                | IBUS_HYPER_MASK
                | IBUS_META_MASK))
            != 0;

        if has_modifiers {
            debug_println!("--> handle_key ignored (has modifiers: state={:#x})", state);
            self.commit_and_reset(signal_emitter, input_mode).await;
            return false;
        }

        if keyval == IBUS_BACKSPACE {
            debug_println!("--> handle_key: Backspace");
            return self.handle_backspace(signal_emitter, input_mode).await;
        }
        if keyval == IBUS_RETURN || keyval == IBUS_ESCAPE {
            debug_println!("--> handle_key: Return/Escape");
            self.commit_and_reset(signal_emitter, input_mode).await;
            return false;
        }
        if keyval == IBUS_TAB {
            debug_println!("--> handle_key: Tab");
            self.commit_and_reset(signal_emitter, input_mode).await;
            return false;
        }

        // X11 keysyms in the range 0xff00 to 0xffff are special function keys (e.g. arrows, F1-F12, Home, End)
        // and should not be treated as printable characters.
        if keyval < 0xff00 {
            if let Some(c) = char::from_u32(keyval) {
                if c.is_control() {
                    debug_println!("--> handle_key: control character '{:?}'", c);
                    self.commit_and_reset(signal_emitter, input_mode).await;
                    return false;
                }

                let (can_process, old_text, new_text) = {
                    let mut engine = self.engine.lock().unwrap();
                    if engine.can_process_key(c) {
                        let old = engine.get_processed_string(VIETNAMESE_MODE);
                        engine.process_key(c, VIETNAMESE_MODE);
                        let new = engine.get_processed_string(VIETNAMESE_MODE);
                        debug_println!("--> engine processed key '{}': '{}' -> '{}'", c, old, new);
                        (true, old, new)
                    } else {
                        debug_println!("--> engine cannot process key '{}'", c);
                        (false, String::new(), String::new())
                    }
                };

                if can_process {
                    let encoded_new = encode(&charset, &new_text);
                    if is_backspace_mode(input_mode) {
                        let encoded_old = encode(&charset, &old_text);
                        let (suffix, n_bs) = get_offset_runes(&encoded_new, &encoded_old);
                        debug_println!("--> is_backspace_mode: suffix='{}', n_bs={}", suffix, n_bs);
                        Self::send_backspace(signal_emitter, input_mode, n_bs).await;
                        if !suffix.is_empty() {
                            let ibus_text = new_ibus_text(&suffix);
                            debug_println!("--> committing suffix: '{}'", suffix);
                            let _ = Self::commit_text(signal_emitter, Value::from(ibus_text)).await;
                        }
                        let mut lt = self.last_text.lock().unwrap();
                        *lt = encoded_new;
                    } else {
                        debug_println!("--> updating preedit: '{}'", encoded_new);
                        let ibus_text = new_ibus_text(&encoded_new);
                        let _ = Self::update_preedit_text(
                            signal_emitter,
                            Value::from(ibus_text),
                            encoded_new.chars().count() as u32,
                            true,
                            1,
                        )
                        .await;
                    }
                    return true;
                } else if is_word_break_symbol(c) {
                    debug_println!("--> is_word_break_symbol: '{}'", c);
                    let old_text = {
                        let mut engine = self.engine.lock().unwrap();
                        let old = engine.get_processed_string(VIETNAMESE_MODE);
                        engine.reset();
                        old
                    };

                    let encoded_old = encode(&charset, &old_text);
                    let committed = format!("{}{}", encoded_old, c);
                    if is_backspace_mode(input_mode) {
                        debug_println!("--> backspace_mode committing: '{}'", c);
                        let ibus_text = new_ibus_text(&c.to_string());
                        let _ = Self::commit_text(signal_emitter, Value::from(ibus_text)).await;
                        let mut lt = self.last_text.lock().unwrap();
                        lt.clear();
                    } else {
                        debug_println!("--> committing final word: '{}'", committed);
                        let ibus_text = new_ibus_text(&committed);
                        let _ = Self::commit_text(signal_emitter, Value::from(ibus_text)).await;
                        let _ = Self::hide_preedit_text(signal_emitter).await;
                    }
                    return true;
                }
            }
        }

        debug_println!("--> handle_key fallback: commit_and_reset and returning false");
        self.commit_and_reset(signal_emitter, input_mode).await;
        false
    }

    /// Internal handler to process the Backspace keystroke.
    /// Returns true if handled by removing characters from the preedit buffer.
    pub async fn handle_backspace(
        &self,
        signal_emitter: &SignalEmitter<'_>,
        input_mode: i32,
    ) -> bool {
        let (preedit_is_empty, new_text) = {
            let mut engine = self.engine.lock().unwrap();
            let preedit = engine.get_processed_string(VIETNAMESE_MODE);
            if preedit.is_empty() {
                (true, String::new())
            } else {
                engine.remove_last_char(true);
                let new_t = engine.get_processed_string(VIETNAMESE_MODE);
                (false, new_t)
            }
        };

        if preedit_is_empty {
            return false;
        }

        let config = load_config();
        let charset =
            CharsetEncoding::from_str(&config.charset).unwrap_or(CharsetEncoding::Unicode);
        let encoded_text = encode(&charset, &new_text);

        if is_backspace_mode(input_mode) {
            let mut lt = self.last_text.lock().unwrap();
            *lt = encoded_text;
            false
        } else {
            if encoded_text.is_empty() {
                let _ = Self::hide_preedit_text(signal_emitter).await;
            } else {
                let ibus_text = new_ibus_text(&encoded_text);
                let _ = Self::update_preedit_text(
                    signal_emitter,
                    Value::from(ibus_text),
                    encoded_text.chars().count() as u32,
                    true,
                    1,
                )
                .await;
            }
            true
        }
    }

    /// Commits any active preedit buffer to the client application and resets the engine.
    pub async fn commit_and_reset(&self, signal_emitter: &SignalEmitter<'_>, input_mode: i32) {
        let preedit = {
            let mut engine = self.engine.lock().unwrap();
            let preedit = engine.get_processed_string(VIETNAMESE_MODE);
            engine.reset();
            preedit
        };

        if !preedit.is_empty() {
            if is_backspace_mode(input_mode) {
                let mut lt = self.last_text.lock().unwrap();
                lt.clear();
            } else {
                let config = load_config();
                let charset =
                    CharsetEncoding::from_str(&config.charset).unwrap_or(CharsetEncoding::Unicode);
                let encoded = encode(&charset, &preedit);
                let ibus_text = new_ibus_text(&encoded);
                let _ = Self::commit_text(signal_emitter, Value::from(ibus_text)).await;
                let _ = Self::hide_preedit_text(signal_emitter).await;
            }
        }
    }

    /// Simulates sending Backspace commands depending on the active input mode.
    pub async fn send_backspace(signal_emitter: &SignalEmitter<'_>, im_mode: i32, n: usize) {
        if n == 0 {
            return;
        }
        debug_println!("--> send_backspace: mode={}, n={}", im_mode, n);
        match im_mode {
            SURROUNDING_TEXT_IM => {
                let _ = Self::delete_surrounding_text(signal_emitter, -(n as i32), n as u32).await;
            }
            BACKSPACE_FORWARDING_IM | FORWARD_AS_COMMIT_IM => {
                for _ in 0..n {
                    let _ = Self::forward_key_event(signal_emitter, IBUS_BACKSPACE, 22, 0).await;
                    let _ = Self::forward_key_event(
                        signal_emitter,
                        IBUS_BACKSPACE,
                        22,
                        IBUS_RELEASE_MASK,
                    )
                    .await;
                }
            }
            SHIFT_LEFT_FORWARDING_IM => {
                for _ in 0..n {
                    let _ =
                        Self::forward_key_event(signal_emitter, IBUS_LEFT, 113, IBUS_SHIFT_MASK)
                            .await;
                    let _ =
                        Self::forward_key_event(signal_emitter, IBUS_LEFT, 113, IBUS_RELEASE_MASK)
                            .await;
                }
            }
            XTEST_FAKE_KEY_EVENT_IM => {
                x11_helper::x11_send_backspace(n, 10);
            }
            _ => {}
        }
    }
}

/// The main IBus Factory instance responsible for creating `IBusEngine` sessions.
pub struct IBusFactory {
    /// The session connection.
    pub connection: Connection,
}

impl IBusFactory {
    /// Creates a new `IBusFactory` instance.
    pub fn new(connection: Connection) -> Self {
        Self { connection }
    }
}

#[interface(name = "org.freedesktop.IBus.Factory")]
impl IBusFactory {
    /// D-Bus method invoked by IBus to spawn a new input method engine layout.
    async fn create_engine(
        &self,
        engine_name: String,
    ) -> Result<OwnedObjectPath, zbus::fdo::Error> {
        println!("Creating engine for layout: {}", engine_name);

        let config = load_config();
        let active_layout = &config.input_method;
        let im_def = get_input_method(active_layout).ok_or_else(|| {
            zbus::fdo::Error::Failed(format!("Input method {} not found", active_layout))
        })?;
        let engine = Engine::new(im_def, config.flags);
        let ibus_engine = IBusEngine::new(engine);

        let path = format!(
            "/org/freedesktop/IBus/Engine/buffalo/{}",
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        );
        let obj_path =
            OwnedObjectPath::try_from(path).map_err(|e| zbus::fdo::Error::Failed(e.to_string()))?;

        self.connection
            .object_server()
            .at(&obj_path, ibus_engine)
            .await
            .map_err(|e| zbus::fdo::Error::Failed(e.to_string()))?;

        Ok(obj_path)
    }
}

/// Runs the main IBus Buffalo input method daemon loop.
/// Resolves the IBus address, connects to the D-Bus session, and registers
/// the IBus Factory service.
pub async fn run_daemon() -> Result<(), Box<dyn std::error::Error>> {
    println!("Starting ibus-buffalo daemon...");
    x11_helper::set_x_ignore_error_handler();

    let addr = get_ibus_address().expect("Could not find IBus daemon address");
    println!("Connecting to IBus daemon at address: {}", addr);

    let connection = Builder::address(addr.as_str())?.build().await?;

    println!("Requesting name: org.freedesktop.IBus.buffalo");
    connection
        .request_name("org.freedesktop.IBus.buffalo")
        .await?;

    println!("Publishing IBus Factory service at /org/freedesktop/IBus/Factory");
    let factory = IBusFactory {
        connection: connection.clone(),
    };
    connection
        .object_server()
        .at("/org/freedesktop/IBus/Factory", factory)
        .await?;

    println!("Daemon successfully started. Waiting for connections...");
    std::future::pending::<()>().await;

    Ok(())
}

/// Helper to determine the path of the UI executable.
///
/// It first checks the directory of the currently running daemon executable
/// (useful for running from target/debug or target/release during development).
/// If not found, it falls back to the default installation path `/usr/lib/ibus-buffalo/buffalo-ui`.
pub fn get_ui_executable_path() -> PathBuf {
    if let Ok(mut exe_path) = std::env::current_exe() {
        exe_path.pop(); // Remove the executable name, leaving the parent directory
        let local_ui = exe_path.join("buffalo-ui");
        if local_ui.exists() {
            return local_ui;
        }
    }
    PathBuf::from("/usr/lib/ibus-buffalo/buffalo-ui")
}
