use std::env;
use std::fs;
use std::path::PathBuf;
use zbus::Connection;

/// Mask representing the Shift key state in IBus.
pub const IBUS_SHIFT_MASK: u32 = 1 << 0;
/// Mask representing the Caps Lock key state in IBus.
pub const IBUS_LOCK_MASK: u32 = 1 << 1;
/// Mask representing the Control key state in IBus.
pub const IBUS_CONTROL_MASK: u32 = 1 << 2;
/// Mask representing the Alt/Mod1 key state in IBus.
pub const IBUS_MOD1_MASK: u32 = 1 << 3;
/// Mask representing the Mod4/Super key state in IBus.
pub const IBUS_MOD4_MASK: u32 = 1 << 6;
/// Mask representing the Super key state in IBus.
pub const IBUS_SUPER_MASK: u32 = 1 << 26;
/// Mask representing the Hyper key state in IBus.
pub const IBUS_HYPER_MASK: u32 = 1 << 27;
/// Mask representing the Meta key state in IBus.
pub const IBUS_META_MASK: u32 = 1 << 28;
/// Mask indicating a key release event in IBus.
pub const IBUS_RELEASE_MASK: u32 = 1 << 30;

/// Key code representing the Backspace key.
pub const IBUS_BACKSPACE: u32 = 0xff08;
/// Key code representing the Tab key.
pub const IBUS_TAB: u32 = 0xff09;
/// Key code representing the Left Arrow key.
pub const IBUS_LEFT: u32 = 0xff51;
/// Key code representing the Return/Enter key.
pub const IBUS_RETURN: u32 = 0xff0d;
/// Key code representing the Escape key.
pub const IBUS_ESCAPE: u32 = 0xff1b;

/// Preedit Input Mode: show composition inline with underlining.
pub const PREEDIT_IM: i32 = 1;
/// Surrounding Text Input Mode: edit surrounding characters directly.
pub const SURROUNDING_TEXT_IM: i32 = 2;

/// Retrieves the unique machine ID from `/var/lib/dbus/machine-id` or `/etc/machine-id`.
/// Returns an empty string if it cannot be read.
pub fn get_local_machine_id() -> String {
    fs::read_to_string("/var/lib/dbus/machine-id")
        .or_else(|_| fs::read_to_string("/etc/machine-id"))
        .unwrap_or_default()
        .trim()
        .to_string()
}

/// Retrieves the path to the user's config directory, honoring `XDG_CONFIG_HOME`
/// with a fallback to `$HOME/.config`.
pub fn get_user_config_dir() -> PathBuf {
    if let Ok(dir) = env::var("XDG_CONFIG_HOME") {
        PathBuf::from(dir)
    } else {
        let home = env::var("HOME").unwrap_or_default();
        PathBuf::from(home).join(".config")
    }
}

/// Detects the active IBus address by reading the environment variable `IBUS_ADDRESS`
/// or by scanning configuration files generated by IBus for Wayland/X11 sessions.
pub fn get_ibus_address() -> Option<String> {
    if let Ok(addr) = env::var("IBUS_ADDRESS") {
        return Some(addr);
    }

    let machine_id = get_local_machine_id();
    if machine_id.is_empty() {
        return None;
    }

    // Check Wayland
    if let Ok(wayland_display) = env::var("WAYLAND_DISPLAY") {
        let filename = format!("{}-unix-{}", machine_id, wayland_display);
        let path = get_user_config_dir().join("ibus/bus").join(filename);
        if let Ok(content) = fs::read_to_string(path) {
            for line in content.lines() {
                if line.starts_with("IBUS_ADDRESS=") {
                    return Some(line["IBUS_ADDRESS=".len()..].to_string());
                }
            }
        }
    }

    // Check X11
    let display = env::var("DISPLAY").unwrap_or_else(|_| ":0".to_string());
    let display_part = display.split(':').nth(1).unwrap_or("0");
    let display_num = display_part.split('.').next().unwrap_or("0");

    let filename = format!("{}-unix-{}", machine_id, display_num);
    let path = get_user_config_dir().join("ibus/bus").join(filename);
    if let Ok(content) = fs::read_to_string(path) {
        for line in content.lines() {
            if line.starts_with("IBUS_ADDRESS=") {
                return Some(line["IBUS_ADDRESS=".len()..].to_string());
            }
        }
    }

    None
}

/// Determines whether the input mode uses simulated backspace inputs to edit text.
pub fn is_backspace_mode(im: i32) -> bool {
    im == SURROUNDING_TEXT_IM
}

/// Returns true if the key event represents a modifier key (Shift, Ctrl, Alt, Super, etc.).
pub fn is_modifier_key(keyval: u32) -> bool {
    (keyval >= 0xffe1 && keyval <= 0xffee) || keyval == 0xfe03 || keyval == 0xff7e
}

/// Calculates the suffix to append and the number of backspaces needed to transition
/// from `old_text` to `new_text`.
pub fn get_offset_runes(new_text: &str, old_text: &str) -> (String, usize) {
    let mut new_chars = new_text.chars();
    let mut old_chars = old_text.chars();
    let mut common_prefix_len = 0;

    loop {
        match (new_chars.next(), old_chars.next()) {
            (Some(n), Some(o)) if n == o => {
                common_prefix_len += 1;
            }
            _ => break,
        }
    }

    let n_backspace = old_text.chars().count() - common_prefix_len;
    let suffix: String = new_text.chars().skip(common_prefix_len).collect();

    (suffix, n_backspace)
}

/// Helper to determine the path of the UI executable.
///
/// It first checks the directory of the currently running daemon executable
/// (useful for running from target/debug or target/release during development).
/// If not found, it falls back to the default installation path `/usr/lib/ibus-buffalo/buffalo-ui`.
pub fn get_ui_executable_path() -> PathBuf {
    if let Ok(mut exe_path) = std::env::current_exe() {
        exe_path.pop(); // Remove the executable name, leaving the parent directory
        let local_ui = exe_path.join("buffalo-ui");
        if local_ui.exists() {
            return local_ui;
        }
    }
    PathBuf::from("/usr/lib/ibus-buffalo/buffalo-ui")
}

/// Queries the GNOME Shell D-Bus interface to retrieve the window class of the focused window.
pub async fn gnome_get_focus_window_class() -> Option<String> {
    let conn = Connection::session().await.ok()?;
    let js_code = "global.get_window_actors().find(window => !Main.overview.visible && window.meta_window.has_focus()).get_meta_window().get_wm_class()";
    let reply: (bool, String) = conn
        .call_method(
            Some("org.gnome.Shell"),
            "/org/gnome/Shell",
            Some("org.gnome.Shell"),
            "Eval",
            &(js_code,),
        )
        .await
        .ok()?
        .body()
        .deserialize()
        .ok()?;

    if reply.0 {
        let s = reply.1.trim().replace('"', "");
        if s.is_empty() || s == "null" {
            None
        } else {
            Some(s)
        }
    } else {
        let is_overview_js = "Main.overview.visible";
        let is_overview_reply: (bool, String) = conn
            .call_method(
                Some("org.gnome.Shell"),
                "/org/gnome/Shell",
                Some("org.gnome.Shell"),
                "Eval",
                &(is_overview_js,),
            )
            .await
            .ok()?
            .body()
            .deserialize()
            .ok()?;

        if is_overview_reply.0 && is_overview_reply.1 == "true" {
            Some("org.gnome.Overview".to_string())
        } else {
            None
        }
    }
}

/// Retrieves the window class of the currently focused window, checking GNOME Shell via D-Bus
/// and falling back to direct X11 queries.
pub async fn get_focus_window_class() -> String {
    if let Some(wm) = gnome_get_focus_window_class().await {
        return wm;
    }
    if let Some(wm) = crate::x11_helper::x11_get_focus_window_class() {
        return wm;
    }
    String::new()
}
